Algoritmo "Problema idades"

Var
   pessoaUm , pessoaDois : caractere
   idadePessoaUm, idadePessoaDois , media: real
Inicio
   escreval("------primeira pessoa------")
   escreval
   escreva(" digite um nome: ")
   leia(pessoaUm)
   escreva(" digite a idade: ")
   leia(idadePessoaUm)
   escreval
   escreval("------segunda pessoa-------")
   escreval
   escreva(" digite um nome: ")
   leia(pessoaDois)
   escreva(" digite a idade: ")
   leia(idadePessoaDois)
   escreval
   escreval("-------idade media---------")
   escreval
   
   media <- (idadePessoaUm + idadePessoaDois) / 2
   
   escreval("A idade média de ", PessoaUm, " e ", pessoaDois, " é de", media, " anos")
   


Fimalgoritmo