Algoritmo "pagamento"

Var

 nome : caractere
 vpHora, hTrabalhadas , pagamento : real

Inicio
 escreval("----------digite os dados----------")
 escreval
 escreva("nome: ")
 leia(nome)
 escreva("Valor por hora: ")
 leia(vpHora)
 escreva("Horas trabalhadas: ")
 leia(hTrabalhadas)
 escreval
 escreval("-----------------------------------")

 pagamento <- vpHora * htrabalhadas
 
 escreval("O pagamento para ", nome, " deve ser de ", pagamento:8:2)
 
 
 

Fimalgoritmo