Algoritmo "senha_fixa"
//
//
// Descrição   :
// Autor(a)    : Marcio Renan
// Data atual  : 27/03/2023
Var
   senha : inteiro


Inicio

   escreva("Digite a senha: ")
   leia(senha)

   enquanto senha <> 2002 faca
      escreva("Senha Invalida! Tente novamente: ")
      leia(senha)
   fimenquanto
   
   se senha = 2002 entao
      escreval
      escreval("Acesso permitido!")
   fimse

Fimalgoritmo